# seclorum/models/code.py
from pydantic import BaseModel
from typing import Optional

class CodeOutput(BaseModel):
    code: str
    tests: Optional[str] = None  # Test code generated by GeneratorAgent

class TestResult(BaseModel):
    test_code: str
    passed: bool
    output: Optional[str] = None
